version: "2.2"

services:
  svn:
    image: 'garethflowers/svn-server:latest'
    restart: unless-stopped
    ports:
      - '3690:3690'
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - './svn/home:/var/opt/svn'
    cpus: '1'
    mem_limit: 200m
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "2"

